### PR TITLE
Fixes #72: "[lua]: Couldn't find message for key config.*" console spam.

### LINKED ISSUE #72: Many "Couldn't find message for key" errors when running VS Code
Since a recent update to this extension (I'm not sure which one, sorry), I've started seeing errors like the below whenever I run `code` from a terminal (e.g. when provisioning vscode extensions from shell scripts).

Although it doesn't break anything, it does bloat the output of scripts and obfuscates important messages.

The values listed don't appear in the extension's `package.nls.json` file, so presumably resolving the issue should be as simple as adding them?

Thanks for all of your work on a great extension!

```
[lua]: Couldn't find message for key config.diagnostics.circle-doc-class.
[lua]: Couldn't find message for key config.diagnostics.invisible.
[lua]: Couldn't find message for key config.diagnostics.circle-doc-class.
[lua]: Couldn't find message for key config.diagnostics.invisible.
[lua]: Couldn't find message for key config.runtime.builtin.basic.
[lua]: Couldn't find message for key config.runtime.builtin.bit.
[lua]: Couldn't find message for key config.runtime.builtin.bit32.
[lua]: Couldn't find message for key config.runtime.builtin.builtin.
[lua]: Couldn't find message for key config.runtime.builtin.coroutine.
[lua]: Couldn't find message for key config.runtime.builtin.debug.
[lua]: Couldn't find message for key config.runtime.builtin.ffi.
[lua]: Couldn't find message for key config.runtime.builtin.io.
[lua]: Couldn't find message for key config.runtime.builtin.jit.
[lua]: Couldn't find message for key config.runtime.builtin.math.
[lua]: Couldn't find message for key config.runtime.builtin.os.
[lua]: Couldn't find message for key config.runtime.builtin.package.
[lua]: Couldn't find message for key config.runtime.builtin.string.
[lua]: Couldn't find message for key config.runtime.builtin.string.buffer.
[lua]: Couldn't find message for key config.runtime.builtin.table.
[lua]: Couldn't find message for key config.runtime.builtin.table.clear.
[lua]: Couldn't find message for key config.runtime.builtin.table.new.
[lua]: Couldn't find message for key config.runtime.builtin.utf8.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf8.
[lua]: Couldn't find message for key config.runtime.fileEncoding.ansi.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf16le.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf16be.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.1.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.2.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.3.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.4.
[lua]: Couldn't find message for key config.runtime.version.LuaJIT.
[lua]: Couldn't find message for key config.typeFormat.config.
[lua]: Couldn't find message for key config.typeFormat.config.auto_complete_end.
[lua]: Couldn't find message for key config.typeFormat.config.auto_complete_table_sep.
[lua]: Couldn't find message for key config.typeFormat.config.format_line.
[lua]: Couldn't find message for key config.diagnostics.circle-doc-class.
[lua]: Couldn't find message for key config.diagnostics.invisible.
[lua]: Couldn't find message for key config.diagnostics.circle-doc-class.
[lua]: Couldn't find message for key config.diagnostics.invisible.
[lua]: Couldn't find message for key config.runtime.builtin.basic.
[lua]: Couldn't find message for key config.runtime.builtin.bit.
[lua]: Couldn't find message for key config.runtime.builtin.bit32.
[lua]: Couldn't find message for key config.runtime.builtin.builtin.
[lua]: Couldn't find message for key config.runtime.builtin.coroutine.
[lua]: Couldn't find message for key config.runtime.builtin.debug.
[lua]: Couldn't find message for key config.runtime.builtin.ffi.
[lua]: Couldn't find message for key config.runtime.builtin.io.
[lua]: Couldn't find message for key config.runtime.builtin.jit.
[lua]: Couldn't find message for key config.runtime.builtin.math.
[lua]: Couldn't find message for key config.runtime.builtin.os.
[lua]: Couldn't find message for key config.runtime.builtin.package.
[lua]: Couldn't find message for key config.runtime.builtin.string.
[lua]: Couldn't find message for key config.runtime.builtin.string.buffer.
[lua]: Couldn't find message for key config.runtime.builtin.table.
[lua]: Couldn't find message for key config.runtime.builtin.table.clear.
[lua]: Couldn't find message for key config.runtime.builtin.table.new.
[lua]: Couldn't find message for key config.runtime.builtin.utf8.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf8.
[lua]: Couldn't find message for key config.runtime.fileEncoding.ansi.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf16le.
[lua]: Couldn't find message for key config.runtime.fileEncoding.utf16be.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.1.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.2.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.3.
[lua]: Couldn't find message for key config.runtime.version.Lua 5.4.
[lua]: Couldn't find message for key config.runtime.version.LuaJIT.
[lua]: Couldn't find message for key config.typeFormat.config.
[lua]: Couldn't find message for key config.typeFormat.config.auto_complete_end.
[lua]: Couldn't find message for key config.typeFormat.config.auto_complete_table_sep.
[lua]: Couldn't find message for key config.typeFormat.config.format_line.
```

### PR DESCRIPTION
**Pull request by notpeter**
Currently when VSCode is launched from the CLI with `code` the console is spammed with a bunch of output. This fixes that.

I believe the errors occur because in Javascript: `Boolean('') == false`.

By replacing it with a placeholder value `"TODO: Needs documentation"` it becomes 'truthy' and no longer complains about missing messages.

* Fixes: #72.
* Fixes: [LuaLS/lua-language-server#1845](https://github.com/LuaLS/lua-language-server/issues/1845)
* See also: https://github.com/LuaLS/vscode-lua/commit/e6b153552866a565a91d94de465873c6cc754ad7

### CODE REVIEW

**Comment by sumneko** [comment]
Thank you! But it sounds like a VSCode issue. Maybe you could also submit a PR at the VSCode repository?

**Comment by notpeter** [comment]
Yeah, I think that used to be [microsoft/vscode-nls](https://github.com/microsoft/vscode-nls) but now it's [microsoft/vscode-l10n](https://github.com/microsoft/vscode-l10n/) (aka `@vscode/l10n-dev`). Maybe I'll take a peek.

**Comment by aungkhant0911** [comment]
Not sure if it was fixed. I still have the same problem. Basically the extension host terminates as soon as .Lua file is opened.

```
`2023-10-25 03:17:43.128 [info] update#setState idle

2023-10-25 03:18:13.133 [info] update#setState checking for updates

2023-10-25 03:18:13.213 [info] update#setState idle

2023-10-25 03:18:27.655 [info] Extension host with pid 17704 exited with code: -1073741795, signal: unknown.

2023-10-25 03:18:27.655 [error] [UtilityProcess id: 1, type: extensionHost, pid: 17704]: crashed with code -1073741795 and reason 'crashed'

2023-10-25 03:18:28.336 [info] Extension host with pid 7756 exited with code: 0, signal: unknown.

2023-10-25 03:18:28.336 [error] [UtilityProcess id: 2, type: extensionHost, pid: 7756]: crashed with code -1073741795 and reason 'crashed'

2023-10-25 03:18:29.016 [info] Extension host with pid 15552 exited with code: 0, signal: unknown.

2023-10-25 03:18:29.028 [error] [UtilityProcess id: 3, type: extensionHost, pid: 15552]: crashed with code -1073741795 and reason 'crashed'





2023-10-25 03:17:45.830 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

2023-10-25 03:17:45.840 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

2023-10-25 03:17:50.918 [info] [perf] Render performance baseline is 35ms

2023-10-25 03:18:04.031 [warning] [lua]: Couldn't find message for key config.diagnostics.circle-doc-class.

2023-10-25 03:18:04.032 [warning] [lua]: Couldn't find message for key config.diagnostics.inject-field.

2023-10-25 03:18:04.032 [warning] [lua]: Couldn't find message for key config.diagnostics.missing-fields.

2023-10-25 03:18:04.032 [warning] [lua]: Couldn't find message for key config.diagnostics.circle-doc-class.

2023-10-25 03:18:04.032 [warning] [lua]: Couldn't find message for key config.diagnostics.inject-field.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.diagnostics.missing-fields.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.runtime.builtin.basic.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.runtime.builtin.bit.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.runtime.builtin.bit32.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.runtime.builtin.builtin.

2023-10-25 03:18:04.033 [warning] [lua]: Couldn't find message for key config.runtime.builtin.coroutine.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.debug.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.ffi.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.io.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.jit.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.jit.profile.

2023-10-25 03:18:04.034 [warning] [lua]: Couldn't find message for key config.runtime.builtin.jit.util.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.math.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.os.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.package.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.string.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.string.buffer.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.table.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.table.clear.

2023-10-25 03:18:04.035 [warning] [lua]: Couldn't find message for key config.runtime.builtin.table.new.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.builtin.utf8.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.fileEncoding.utf8.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.fileEncoding.ansi.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.fileEncoding.utf16le.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.fileEncoding.utf16be.

2023-10-25 03:18:04.036 [warning] [lua]: Couldn't find message for key config.runtime.version.Lua 5.1.

2023-10-25 03:18:04.037 [warning] [lua]: Couldn't find message for key config.runtime.version.Lua 5.2.

2023-10-25 03:18:04.037 [warning] [lua]: Couldn't find message for key config.runtime.version.Lua 5.3.

2023-10-25 03:18:04.037 [warning] [lua]: Couldn't find message for key config.runtime.version.Lua 5.4.

2023-10-25 03:18:04.037 [warning] [lua]: Couldn't find message for key config.runtime.version.LuaJIT.

2023-10-25 03:18:27.660 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.

2023-10-25 03:18:27.660 [info] Automatically restarting the extension host.

2023-10-25 03:18:28.359 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.

2023-10-25 03:18:28.359 [info] Automatically restarting the extension host.

2023-10-25 03:18:29.032 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were `activated.``
```

**Comment by carsakiller** [comment]
@aungkhant0911 you appear to have a larger problem that what this PR is about. The VS Code extension host (the runtime that runs all extensions) crashing is unrelated but concerning. Can you try disabling all extensions except for the Lua extension and try to replicate the issue? If it persists with the Lua extension, please open an issue.

As for the Lua log messages, there has not been a release yet that contains this fix.

**Comment by aungkhant0911** [comment]
I only have one extension and that is this one.  Other extensions which were uninstalled (because I was testing) worked just fine. Eg; Pylance/Python debug codes just fine. Only this one got a problem.

**Comment by notpeter** [comment]
Please open a new issue. This issue is related to a bunch of excessive warnings that are outputted to the console.

You are seeing these but they are harmless and unrelated to your crashing issue.

**Pull request merged**
